### ISSUE TITLE
`mgmt` bridge breaks default `tc` token bucket filtering qdisc

### ISSUE THREAD

**Issue by zv** [Pathangi-Jatinshravan/kvm_network_initializer#1]
The default Linux traffic control mechanism `tc`, ships with a token bucket filtering queuing discipline which utilizes the bridge named `mgmt` as a logical policy bridge which conflicts with the bridge naming convention used here.

Another bridge name such as _kvm_ni_mgmt_ or _ni_management_ will fix this issue and reduce the risk of conflicts and confusion, particularly for developers trying it out.

Great work by the way!

**Comment by Pathangi-Jatinshravan** [comment]
Thanks. I have changed it so that the management and dummy bridge names can be given in the config file itself. It is defaulted to 'cust_management' and 'cust_dummy' respectively.

**Comment by zv** [comment]
Pulled the latest version and tried out the custom bridge naming, everything is chugging along at high speed.

Thank you for your expedient response.
